### ISSUE TITLE
tfgrid3: support minimal farmer bot features

### ISSUE THREAD

**Issue by maxux** [threefoldtech/digitaltwin#100]
Dedicated part of the digital twin for farmer needs to support couple of things:
- [x] Create a farm
- [x] Support node registration into a farm
- [ ] Support `clusters` (one farm can get multiple cluster)
- [ ] Support capacity reporting
- [ ] Enable post-billing
- [ ] Support node external configuration

Clusters are group of nodes which shares group of publics IPs available for gateways. They are protected by a pre-shared key which nodes will send on boot.

Capacity reporting is where nodes pushes their usage for each customers, to the farm, so the farm can request billing.

Billing is requesting payment from customers, from the farmer bot.

**Comment by muhamadazmy** [comment]
Deprecated, no farmer bot anymore, instead this gonna be on the chain directly
