### ISSUE TITLE
Add security - W10

### ISSUE THREAD

**Issue by ken-de-moor** [threefoldtech/digitaltwin#115]
Okay so security will need to be handled in multiple layers: 

**1. Session security.**
First off we have session security, a user should only be able to login to their own digitaltwin once authenticated. 
This will be accomplished by providing a sessionID when a user does a valid login.

**2. Application security.**
The application should not contain any security vulnerabilities such as XSS / SQLi / Directory traversal / ...

**3. Network security. (end / end using yggdrasil)**
Communication between digital twins should be using yggdrasil and these IPs should be registered in the TFDB and verified in the individual digital twins. 

**4. Usability security / access control security.**
Text-length limitations and character limitations should be server-side enforced so people cannot break the chat-flow and pick crazy long status updates. Access-control for file uploads should also be looked at in the future. 

**5. CI/CD deployment security with secrets.**
The backend seedphase should NOT be saved in the config.ts file but rather it should be saved as an environment variable. The same will apply to the secret we will use for **'1. Session security'**

**Other: TFDB problems.**
The TFDB has been post-poned for now and we will implement this functionality in the current threefold-connect database.

**Comment by MathiasDeWeerdt** [comment]
Updated security requirements.

**Comment by ken-de-moor** [comment]
- Implement sessions
- not being able to go directly to /chat
