### ISSUE TITLE
Meetings should not require another login.

### ISSUE THREAD

**Issue by ken-de-moor** [threefoldtech/digitaltwin#119]
Should immediately be logged in with 3botconnect

**Comment by ken-de-moor** [comment]
Opened again,

Navigates to

https://freeflowconnect.threefold.me/?roomName=9505be8a4f7f30dd43d9a48ee00edb394787dc3e%26username%3Dkendemoor.3bot

Should be

https://freeflowconnect.threefold.me/?roomName=9505be8a4f7f30dd43d9a48ee00edb394787dc3e&username=kendemoor.3bot

Encoding is wrong which makes the username flow fail.

**Comment by MathiasDeWeerdt** [comment]
Fixed.
