### ISSUE TITLE
Not getting contact requests

### ISSUE THREAD

**Issue by ken-de-moor** [threefoldtech/digitaltwin#126]
Most of the other features are locked behind this, can't continue testing.

![image](https://user-images.githubusercontent.com/59569757/109962582-a9a12080-7ceb-11eb-8244-906d96b508ac.png)

**Comment by ken-de-moor** [comment]
Refreshing doesn't help, following error shown

![image](https://user-images.githubusercontent.com/59569757/109962827-f84eba80-7ceb-11eb-956a-a0bdf155756b.png)

**Comment by MathiasDeWeerdt** [comment]
Fixed.
