### ISSUE TITLE
Chat no longer receives messages.

### ISSUE THREAD

**Issue by ken-de-moor** [threefoldtech/digitaltwin#129]
Only chats from one end are being sent, other chats aren't arriving anymore.

Worked for a few messages then just stopped working.

Refreshing the page does not make the messages show up either.

https://user-images.githubusercontent.com/59569757/110090699-d9a5fd80-7d97-11eb-8cd3-fe8866605a44.mp4

**Comment by MathiasDeWeerdt** [comment]
Should be fixed by reworking some things.
