### ISSUE TITLE
incorrect active tab

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/digitaltwin#173]
![image](https://user-images.githubusercontent.com/64129/113114280-76c74b00-920b-11eb-984d-fe963641c984.png)

chat is active on the sidebar, but file storage is showing up

![image](https://user-images.githubusercontent.com/64129/113115081-56e45700-920c-11eb-95f2-d3682360f234.png)

**Comment by ken-de-moor** [comment]
Resolved on staging, aiming for prod deploy within a few days.
