### ISSUE TITLE
creating new directory gives 500 internal server error

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/digitaltwin#175]
![image](https://user-images.githubusercontent.com/64129/113114793-ffde8200-920b-11eb-82e8-f753047e2caf.png)

**Comment by ken-de-moor** [comment]
![image](https://user-images.githubusercontent.com/59569757/114018694-d0fc8780-986d-11eb-9b95-1a5dc0423fd3.png)

Seems to be fixed in prod, just created these without issue.
