### ISSUE TITLE
active area is too small

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/digitaltwin#177]
![image](https://user-images.githubusercontent.com/64129/113116374-ab3c0680-920d-11eb-8762-1348e797bce2.png)

**Comment by ken-de-moor** [comment]
Improvements have been made.

Right sidebar is collapsible.

Smaller widths on mobile will default to mobile view.

Some examples : 

![image](https://user-images.githubusercontent.com/59569757/114018546-a6123380-986d-11eb-8d73-9192f1fa1bbb.png)

![image](https://user-images.githubusercontent.com/59569757/114018572-add1d800-986d-11eb-8029-72e8dc8f428b.png)
