### ISSUE TITLE
sending audio messages shows "file has been uploaded"

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/digitaltwin#180]
![image](https://user-images.githubusercontent.com/64129/113117297-9449e400-920e-11eb-9f6f-e45f45816f07.png)

Should indicate it's a voice message.

**Comment by ken-de-moor** [comment]
Fixed on staging, prod ready in few days.

![image](https://user-images.githubusercontent.com/59569757/119802674-096c2980-bedf-11eb-9875-b731664a6d1d.png)
