### ISSUE TITLE
the user is shown up multiple times when blocked in blocked users

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/digitaltwin#185]
![image](https://user-images.githubusercontent.com/64129/113118178-821c7580-920f-11eb-882d-828e978590ec.png)

**Comment by ken-de-moor** [comment]
Only once now, ( sorry weynand )

![image](https://user-images.githubusercontent.com/59569757/114018099-2b491880-986d-11eb-8ec9-13ca6319238d.png)
