### ISSUE TITLE
replying on messages is delayed

### ISSUE THREAD

**Issue by waleedhammam** [threefoldtech/digitaltwin#188]
![Screenshot from 2021-03-31 11-02-36](https://user-images.githubusercontent.com/10658229/113119385-adec2b00-9210-11eb-9d1d-05f068bd049e.png)

It's chat app shouldn't be like forums(in place). the new messages should appear newely

**Comment by ken-de-moor** [comment]
Fixed internally

**Comment by ken-de-moor** [comment]
Validated on prod

![image](https://user-images.githubusercontent.com/59569757/114017921-f0df7b80-986c-11eb-9fbe-75df08c48394.png)
