### ISSUE TITLE
joined the videoroom isn't clickable

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/digitaltwin#192]
![image](https://user-images.githubusercontent.com/64129/113120289-b8f38b00-9211-11eb-9e45-10951a4a246d.png)

I get the info in the chat "multiple times" probably because the other person tried to join multiple times, but also I'd expect the message to have a clickable link triggering the action of "Join video room"

**Comment by ken-de-moor** [comment]
Fixed internally

**Comment by ken-de-moor** [comment]
Fixed on prod
