### ISSUE TITLE
get the 1.0 experience moved to experience.mydigitaltwin.io

### ISSUE THREAD

**Issue by sasha-astiadi** [threefoldtech/digitaltwin#204]
get the 1.0 experience moved to experience.mydigitaltwin.io
testnet: experience.testnet.mydigitaltwin.io

**Comment by jdelrue** [comment]
As for the "1.0". Should we host this on the grid? Is this currently possible including spawning / payments etc? Whats the plan of action for this?

**Comment by AlexandreHannelas** [comment]
Talk to Kristine, it is possible. 

@Hamdy please check if it is possible with our DNS stream.

**Comment by ken-de-moor** [comment]
Need feedback from technical people on moving this to grid. @jdelrue will organize a meeting.

^ @sasha-astiadi this is the ticket about grid 1.0.0 release.

**Comment by ken-de-moor** [comment]
Ticket went away from original scope. Closed
