### ISSUE TITLE
XSS via getExternalResource

### ISSUE THREAD

**Issue by azertyalex** [threefoldtech/digitaltwin#216]
It is possible to serve your own html and js files on the digitaltwin domain via the getExternalResource parameter.  
Example:
https://amol.digitaltwin.jimbertesting.be/getExternalResource?resource=http://178.62.231.45:8000/index.html

Where an attacker would replace the username with the name of the targeted user.  
Only ip addresses will work because the nginx has no resolver.

Link to code: [nginx.conf#L47](https://github.com/threefoldtech/digitaltwin/blob/main/nginx.conf#L47)

my advice is to put 
```nginx
    add_header Content-disposition "attachment; filename=$arg_resource";
```
in the location block, I'm not sure about the filename variable

**Comment by ken-de-moor** [comment]
Still worked https://kendiedalf.digitaltwin.jimbertesting.be/getExternalResource?resource=http://178.62.231.45:8000/index.html
