### ISSUE TITLE
The layout should be sexy

### ISSUE THREAD

**Issue by ken-de-moor** [threefoldtech/digitaltwin#26]
Not just a standard boring layout, it needs to be sexy, modern. It needs to be the next best thing.

@coeneivan we count on you

**Comment by ken-de-moor** [comment]
Layout is sexy but it can be sexier

Design is made, needs to still be implemented

**Comment by MathiasDeWeerdt** [comment]
Layout is now 'sexy', could still be improved. But this is a process that grows and doesnt magically appear out of thin air.
