### ISSUE TITLE
Accept chat from new contact doesn't work

### ISSUE THREAD

**Issue by ken-de-moor** [threefoldtech/digitaltwin#36]
Cicking it doesn't do anything for me ( on Firefox if that's relevant )

![image](https://user-images.githubusercontent.com/59569757/107241139-fd8d5200-6a2a-11eb-814a-71c89ef6d18d.png)

**Comment by tobiaschielens** [comment]
Will be cause of this issue: https://github.com/threefoldtech/digitaltwin/issues/38
