### ISSUE TITLE
Most of the flag emojis don't work

### ISSUE THREAD

**Issue by ken-de-moor** [threefoldtech/digitaltwin#40]
![image](https://user-images.githubusercontent.com/59569757/107242713-907abc00-6a2c-11eb-9947-366e36f1a505.png)

**Comment by ken-de-moor** [comment]
![image](https://user-images.githubusercontent.com/59569757/107381305-9e8d1300-6ae6-11eb-986b-f82e704280d1.png)

**Comment by tobiaschielens** [comment]
@ken-de-moor can u give browser version, could be browser implementation related

**Comment by ken-de-moor** [comment]
Chrome : Version 88.0.4324.146 (Official Build) (64-bit)


Not a major though

**Comment by MathiasDeWeerdt** [comment]
We changed emoji picker, can u reverify @ken-de-moor ?

**Comment by ken-de-moor** [comment]
Did some research, for some reason windows simply has not implemented flag emojis. @MathiasDeWeerdt apparantly it's political reasons with for example china blocking taiwan flag emojis and stuff... Weird world
