### ISSUE TITLE
"is read" always appears even when not read

### ISSUE THREAD

**Issue by ken-de-moor** [threefoldtech/digitaltwin#55]
My other user's tab is in an inactive tab, in an inactive browser window. So it can't possibly be read.

![image](https://user-images.githubusercontent.com/59569757/107380077-76e97b00-6ae5-11eb-9727-b39a8ee8f0a5.png)

**Comment by JonasWijne** [comment]
currently read means "is rendered" , this needs to be changed to have an intersection observer https://developer.mozilla.org/en-US/docs/Web/API/Intersection_Observer_API and only when active
