### ISSUE TITLE
Chat no longer works even after hard refresh and clear storage. 502 error

### ISSUE THREAD

**Issue by ken-de-moor** [threefoldtech/digitaltwin#61]
Other chats still work, docker logs on my container show connection refused.

![image](https://user-images.githubusercontent.com/59569757/107382211-8bc70e00-6ae7-11eb-9305-d79e4fc4970d.png)

![image](https://user-images.githubusercontent.com/59569757/107382326-a8634600-6ae7-11eb-9244-70ee888920c6.png)

**Comment by tobiaschielens** [comment]
What did you upload before?

**Comment by ken-de-moor** [comment]
No longer getting the issue
