### ISSUE TITLE
Text goes out of bounds

### ISSUE THREAD

**Issue by ken-de-moor** [threefoldtech/digitaltwin#7]
Test with

WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW

Goes out of bounds both in recent messages and in the normal messages field.

**Comment by ken-de-moor** [comment]
Still happens in normal message field.

**Comment by MathiasDeWeerdt** [comment]
Fixed in latest version.

![image](https://user-images.githubusercontent.com/7256303/110604632-95946d80-8188-11eb-86da-9bb47b36ab1d.png)
