### ISSUE TITLE
No user error when filesize > 1MB

### ISSUE THREAD

**Issue by ken-de-moor** [threefoldtech/digitaltwin#74]
Should tell the user why his file upload failed.

"The file you tried to send is over the maximum allowed file size of 1MB"

Also can we change this to 10MB? Is it just a config?

**Comment by tobiaschielens** [comment]
I've changed the implementation from sending an image over the socket to an API call which increased the filesize. Error handling should be implemented still

**Comment by ken-de-moor** [comment]
Bug was specifically for the error handling, so if that isn't fixed then the bug isn't really fixed :D

Just tried with a 50MB file and still no clue why it went wrong, or what the actual limit is
