### ISSUE TITLE
ci/cd production

### ISSUE THREAD

**Issue by JonasWijne** [threefoldtech/digitaltwin#79]

**Comment by MathiasDeWeerdt** [comment]
Github actions CI/CD voor staging en production zijn in orde voor:

- https://github.com/threefoldtech/digitaltwin/
- https://github.com/threefoldtech/digitaltwin_spawner/

Het triggeren van een build / deploy naar staging:
- git tag v0.0.6-rc01
- git push --tags

Het triggeren van een build / deploy naar production:
- git tag v0.0.6
- git push --tags
