### ISSUE TITLE
show version number

### ISSUE THREAD

**Issue by JonasWijne** [threefoldtech/digitaltwin#80]
- Log in console

**Comment by JonasWijne** [comment]
it is logged in console
![image](https://user-images.githubusercontent.com/6184820/108088112-65214e00-7078-11eb-8750-57707d0186bc.png)

**Comment by ken-de-moor** [comment]
commit hash: undefined
![image](https://user-images.githubusercontent.com/59569757/108196151-0b249500-7119-11eb-8e04-57699b5d433d.png)
