### ISSUE TITLE
paste image/file in chat input

### ISSUE THREAD

**Issue by JonasWijne** [threefoldtech/digitaltwin#99]

**Comment by ken-de-moor** [comment]
![image](https://user-images.githubusercontent.com/59569757/110009403-429c5f80-7d1d-11eb-891f-f36a73381194.png)


Doesn't work


<img src="https://kendemoor.digitaltwin-test.jimbertesting.be/getExternalResource?resource=http://[203:6433:e5aa:a69e:ddfa:cc66:ccf1:c367]/api/files/kjjk/image.png">
